### ISSUE TITLE
comentarios avances 2

### ISSUE THREAD

**Issue by AliciaMstt** [tnpalafox/ProyectoFinalBioinf2017-II#2]
Buenas lecturas y avances.

Observaciones:

* Cuida tus links en el formato md, si dejas un espacio después de [] antes de () no se visualizan bien. También ojo con que te falte un espacio después de ### en los títulos.

* Asegúrate de instalar y correr con datos de prueba Stacks LO MÁS PRONTO POSIBLE. No es trivial la instalación incluso utilizando Docker.

Sobre tus preguntas: 

*Tengo una bronca bien básica. Estoy tratando de bajar las secuencias crudas de DRYAD desde mi terminal, para ello estoy usando el comando curl, aquí mi comando (con los ID de cada secuencia)*

efetch no sirve para el sra de igual manera que con las secuenicas (checa la parte de tu línea que dice sequenceid, esa no es la bd donde estás buscando. Prueba https://trace.ncbi.nlm.nih.gov/Traces/sra/sra.cgi?view=search_seq_name.

*En su paper, Alicia hizo un script de Perl personalizado, las muestras con las que cuenta son single single end y justo como esa línea de comando que ella utilizó trabajo con datos pair end, tuvo que hacer una copia y renombrar los archivos fastq para hacer un "fake P2 pair".*

*Ya que yo usaré process_radtags (que acepta tanto datos single como double end) no haré este paso peeeero... ella también quitó la base 70 en todas las lecturas demultiplexeadas ya que un error en secuencias BERL3 que causaba un efecto lane... yo no quiero quitarlo ya que de acuerdo a process_radtags corrige ese tipo de errores , ¿hago y entiendo bien? no quisiera regar el tepache gacho.*

Cuando hicimos el análisis Stacks no permitía demultiplexear este tipo de datos, por eso el script personalizado. Las lecturas del SRA ya no incluyen la base 70 pues era basura, así que no puedes correr estos análisis con process_radtags.

**Comment by tnpalafox** [comment]
Hola Alicia

Hice el ensamblado de novo con stacks de las muestras de B. alpina, las tomé como 7 poblaciones (que son 7 los sitios de colecta de acuerdo con los datos que revisé de NCBI). Todo iba lentísimo, duró días corriendo y eso que son solo 75 muestras. Al final  me arrojó el mensaje que te adjunto.
![captura de pantalla 2017-05-26 a las 7 03 26 p m](https://cloud.githubusercontent.com/assets/25498450/26516314/df333c50-4249-11e7-845f-f90ccca3542c.png)

Chequé mis rutas de input y de output y los parámetros que le dí; no hay error.
Busqué ayuda en la red y algunas personas han tenido el mismo problema, Julian Catchen contestó lo siguiente a un chico:
_"you will need to trim and and reprocess your files for ustacks
first, the error may have been caused by ustacks outputting bad data
when the lengths of reads were different in a single individual."_

Y esto a otra chica: 
_"Hi Vanessa,
Yes, you need sequences of the same length. The pipeline is trying to
identify the same SNPs consistently across individuals in your set of
populations. If you have variable length reads, you will simply add a
lot of poorly covered SNP calls and higher error rates associated with them.
If you received quality trimmed reads from your sequencing core, you
should ask for the original, unmodified files.
Otherwise, you can specify a final length of the reads to the
process_radtags program, which will trim reads to that length and
discard reads already shorter than that length."_

Yo cuento con los datos ya demultiplexeados y procesados, así que ya no sé que hacer. Ese mensaje me partió mi corazón , por no decir la madre, ya que después de días corriendo sale eso y ya tenía lista mi línea de comando para correr populations. ¿Que me recomiendas hacer? Disculpa que te dé lata pero estoy muy angustiada.

Muchas gracias y que pases bonita noche.

**Comment by tnpalafox** [comment]
@AliciaMstt Por cierto, olvidé mencionarte que en mi carpeta output sí están los archivos que arrojó por muestra, mira: 
![captura de pantalla 2017-05-26 a las 7 40 16 p m](https://cloud.githubusercontent.com/assets/25498450/26516386/32f0f69c-424b-11e7-9217-98d2fe396db8.png)
